var subject = require('./subject.js')
var mock = require('mock-fs');
subject.inc('',undefined);
subject.inc(-1,'');
subject.inc(-1,undefined);
subject.inc(-1,NaN);
subject.inc(0,NaN);
subject.inc(0,NaN);
subject.weird(8,'','','');
subject.weird('',-1,'','');
subject.weird('','',41,'');
subject.weird('','','',"strict");
subject.weird('','','','werw');
subject.weird('','','',"strict");
subject.weird('','','','notstrict');
subject.weird(8,-1,41,'notstrict');
subject.weird(7,-1,41,'notstrict');
subject.weird(7,0,41,'notstrict');
subject.weird(7,0,42,'notstrict');
subject.weird(7,0,42,NaN);
subject.weird(7,0,42,'werw');
subject.weird(7,0,42,"strict");
subject.weird(7,0,42,'notstrict');
subject.weird(7,0,42,'notstrict');
subject.fileTest('path/fileExists','');
subject.fileTest('','path/fileExists');
subject.fileTest('','pathContent/file1');
mock({"path/fileExists":{},"pathContent":{"file1":"text content"}});
	subject.fileTest('path/fileExists','pathContent/file1');
mock.restore();
mock({"path/fileExists":{"some-file.txt":"file content here"},"pathContent":{"file1":"text content"}});
	subject.fileTest('path/fileExists','pathContent/file1');
mock.restore();
mock({"path/fileExists":{}});
	subject.fileTest('path/fileExists','pathContent/file1');
mock.restore();
mock({});
	subject.fileTest('path/fileExists','pathContent/file1');
mock.restore();
mock({"path/fileExists":{"some-file.txt":"file content here"}});
	subject.fileTest('path/fileExists','pathContent/file1');
mock.restore();
mock({"path/fileExists":{"some-file.txt":"file content here"},"pathContent":{"file1":""}});
	subject.fileTest('path/fileExists','pathContent/file1');
mock.restore();
subject.fileTest('path/fileExists','pathContent/file1');
subject.fileTest('path/fileExists','path/fileExists');
subject.fileTest('path/fileExists','pathContent/file1');
subject.fileTest('path/fileExists','pathContent/file1');
subject.normalize('892.116.4270');
subject.normalize('892.116.4270');
subject.format('170.341.0914','',{"normalize":true});
subject.format('170.341.0914','',{"normalize":true});
subject.blackListNumber('212123123');
subject.blackListNumber('213123123');
subject.blackListNumber('213123123');
subject.blackListNumber('212123123');
subject.blackListNumber('213123123');
subject.blackListNumber('213123123');
